### ISSUE TITLE
template.handlebars is timing out on load

### ISSUE THREAD

**Issue by TrikkStar** [TrikkStar/WebApplications_Final#13]
Not sure if I implimented it incorrectly or not. Need to fix to close #11

**Comment by TrikkStar** [comment]
Closed in error

**Comment by TrikkStar** [comment]
@skiadas Do you have any advice on fixing this?

**Comment by skiadas** [comment]
My guess is this has to do with the difference between `"../template.handlebars"` and `"./template.handlebars"`. Two dots does something different than 1 dot. Two dots moves up a directory level. One dot refers to the current level.

**Comment by TrikkStar** [comment]
I know, though when I try a single dot the same error still happens.

**Comment by skiadas** [comment]
Hm I think if you look at the error it should lead you the right way. It seems it does not know what to do about "text!". This is probably because the text plugin for requirejs is not included. Look at the requirejs documentation for information on the text plugin.

In other words requirejs doesn't automatically know what to do about "text!". The documentation for it should tell you how to let it know about it. You'll probably need to download and include a file.

**Comment by TrikkStar** [comment]
That was indeed the case, thank you.
