### ISSUE TITLE
Define is not defined while testing

### ISSUE THREAD

**Issue by TrikkStar** [TrikkStar/WebApplications_Final#25]
When running mocha on `algorithms.spec.js`, I get an error saying tat define is not defined in the first line of `algorithms.js`. Unsure of what is going wrong.

**Comment by skiadas** [comment]
That's because Node doesn't know anything about the AMD modules you are defining. There are two ways about it:

1. Use UMD modules (look at the "AMD and Node Adapter" section of http://skiadas.github.io/WebAppsCourse/site/notes/umd.html). If you structure your files that way, node will be able to read them.
2. Run mocha in the browser. This means:
    - an index-test.html file that is like your index.html, but it loads instead a "app/maintests.js" and probably also loads "mocha.js" and "chai.js". You can find info on how that file would have to look like in the mocha documentation, looking at "running in browser".
    - a "app/maintests.js" that is a little bit like "app/main.js" but that also runs some tests at some point, instead of starting the normal app.
    -

**Comment by TrikkStar** [comment]
In regards to the UMD, which files do I need to do that to?

**Comment by skiadas** [comment]
Pretty much any file that starts with "define" and you want/need to load from node.

On top of that, you need to change your defines a little bit. Instead of taking an array like so:

```
define(["a","b","c"], f(a,b,c) {

})
```

You need to do:

```
define(function(require) {
    var a = require("a");
    var b = require("b");
    var c = require("c");
});
```

You also need to use relative paths, so all starting with "./" or "../" depending.
